<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  <AssemblyName>LmsMini.WebApp.ApiClients</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Classroom\Lesson\_EditLessonModal.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Pages\Classroom\Lesson\_EditLessonModal.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ChatGPT.Net" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    
    <ProjectReference Include="D:\code\last final\LSMI_HUTECH-Phoenix-branch\LmsMini.Application\LmsMini.Application.csproj" />
    <ProjectReference Include="D:\code\last final\LSMI_HUTECH-Phoenix-branch\LmsMini.Domain\LmsMini.Domain.csproj" />
  </ItemGroup>

</Project>
